# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/andrew/eclypse-z7-notes/cfg/clocks.xdc

# XDC: /home/andrew/eclypse-z7-notes/cfg/ports.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_pll_0_0/system_pll_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_pll_0_0 || ORIG_REF_NAME==system_pll_0_0} -quiet] -quiet

# IP: bd/system/ip/system_ps_0_0/system_ps_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ps_0_0 || ORIG_REF_NAME==system_ps_0_0} -quiet] -quiet

# IP: bd/system/ip/system_iic_0_0/system_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_iic_0_0 || ORIG_REF_NAME==system_iic_0_0} -quiet] -quiet

# IP: bd/system/ip/system_gpio_0_0/system_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gpio_0_0 || ORIG_REF_NAME==system_gpio_0_0} -quiet] -quiet

# IP: bd/system/ip/system_gpio_1_0/system_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gpio_1_0 || ORIG_REF_NAME==system_gpio_1_0} -quiet] -quiet

# IP: bd/system/ip/system_const_0_0/system_const_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_const_0_0 || ORIG_REF_NAME==system_const_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_0_0/system_rst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_0_0 || ORIG_REF_NAME==system_rst_0_0} -quiet] -quiet

# IP: bd/system/ip/system_adc_0_0/system_adc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_adc_0_0 || ORIG_REF_NAME==system_adc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_bcast_0_0/system_bcast_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bcast_0_0 || ORIG_REF_NAME==system_bcast_0_0} -quiet] -quiet

# IP: bd/system/ip/system_comb_0_0/system_comb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_comb_0_0 || ORIG_REF_NAME==system_comb_0_0} -quiet] -quiet

# IP: bd/system/ip/system_dac_0_0/system_dac_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_dac_0_0 || ORIG_REF_NAME==system_dac_0_0} -quiet] -quiet

# IP: bd/system/ip/system_hub_0_0/system_hub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_hub_0_0 || ORIG_REF_NAME==system_hub_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_slice_0_0/system_rst_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_slice_0_0 || ORIG_REF_NAME==system_rst_slice_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_slice_1_0/system_rst_slice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_slice_1_0 || ORIG_REF_NAME==system_rst_slice_1_0} -quiet] -quiet

# IP: bd/system/ip/system_cfg_slice_0_0/system_cfg_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cfg_slice_0_0 || ORIG_REF_NAME==system_cfg_slice_0_0} -quiet] -quiet

# IP: bd/system/ip/system_cfg_slice_1_0/system_cfg_slice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cfg_slice_1_0 || ORIG_REF_NAME==system_cfg_slice_1_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_0_0/system_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_0_0 || ORIG_REF_NAME==system_slice_0_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_1_0/system_slice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_1_0 || ORIG_REF_NAME==system_slice_1_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_2_0/system_slice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_2_0 || ORIG_REF_NAME==system_slice_2_0} -quiet] -quiet

# IP: bd/system/ip/system_phase_0_0/system_phase_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_phase_0_0 || ORIG_REF_NAME==system_phase_0_0} -quiet] -quiet

# IP: bd/system/ip/system_dds_0_0/system_dds_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_dds_0_0 || ORIG_REF_NAME==system_dds_0_0} -quiet] -quiet

# IP: bd/system/ip/system_lfsr_0_0/system_lfsr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_lfsr_0_0 || ORIG_REF_NAME==system_lfsr_0_0} -quiet] -quiet

# IP: bd/system/ip/system_mult_0_0/system_mult_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_mult_0_0 || ORIG_REF_NAME==system_mult_0_0} -quiet] -quiet

# IP: bd/system/ip/system_bcast_0_1/system_bcast_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bcast_0_1 || ORIG_REF_NAME==system_bcast_0_1} -quiet] -quiet

# IP: bd/system/ip/system_rate_0_0/system_rate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rate_0_0 || ORIG_REF_NAME==system_rate_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rate_1_0/system_rate_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rate_1_0 || ORIG_REF_NAME==system_rate_1_0} -quiet] -quiet

# IP: bd/system/ip/system_cic_0_0/system_cic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cic_0_0 || ORIG_REF_NAME==system_cic_0_0} -quiet] -quiet

# IP: bd/system/ip/system_cic_1_0/system_cic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cic_1_0 || ORIG_REF_NAME==system_cic_1_0} -quiet] -quiet

# IP: bd/system/ip/system_comb_0_1/system_comb_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_comb_0_1 || ORIG_REF_NAME==system_comb_0_1} -quiet] -quiet

# IP: bd/system/ip/system_conv_0_0/system_conv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_conv_0_0 || ORIG_REF_NAME==system_conv_0_0} -quiet] -quiet

# IP: bd/system/ip/system_fir_0_0/system_fir_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_fir_0_0 || ORIG_REF_NAME==system_fir_0_0} -quiet] -quiet

# IP: bd/system/ip/system_subset_0_0/system_subset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_subset_0_0 || ORIG_REF_NAME==system_subset_0_0} -quiet] -quiet

# IP: bd/system/ip/system_fp_0_0/system_fp_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_fp_0_0 || ORIG_REF_NAME==system_fp_0_0} -quiet] -quiet

# IP: bd/system/ip/system_conv_1_0/system_conv_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_conv_1_0 || ORIG_REF_NAME==system_conv_1_0} -quiet] -quiet

# IP: bd/system/ip/system_fifo_0_0/system_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_fifo_0_0 || ORIG_REF_NAME==system_fifo_0_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_0_1/system_slice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_0_1 || ORIG_REF_NAME==system_slice_0_1} -quiet] -quiet

# IP: bd/system/ip/system_slice_1_1/system_slice_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_1_1 || ORIG_REF_NAME==system_slice_1_1} -quiet] -quiet

# IP: bd/system/ip/system_slice_2_1/system_slice_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_2_1 || ORIG_REF_NAME==system_slice_2_1} -quiet] -quiet

# IP: bd/system/ip/system_fifo_0_1/system_fifo_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_fifo_0_1 || ORIG_REF_NAME==system_fifo_0_1} -quiet] -quiet

# IP: bd/system/ip/system_conv_0_1/system_conv_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_conv_0_1 || ORIG_REF_NAME==system_conv_0_1} -quiet] -quiet

# IP: bd/system/ip/system_fp_0_1/system_fp_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_fp_0_1 || ORIG_REF_NAME==system_fp_0_1} -quiet] -quiet

# IP: bd/system/ip/system_fir_0_1/system_fir_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_fir_0_1 || ORIG_REF_NAME==system_fir_0_1} -quiet] -quiet

# IP: bd/system/ip/system_conv_1_1/system_conv_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_conv_1_1 || ORIG_REF_NAME==system_conv_1_1} -quiet] -quiet

# IP: bd/system/ip/system_bcast_0_2/system_bcast_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bcast_0_2 || ORIG_REF_NAME==system_bcast_0_2} -quiet] -quiet

# IP: bd/system/ip/system_rate_0_1/system_rate_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rate_0_1 || ORIG_REF_NAME==system_rate_0_1} -quiet] -quiet

# IP: bd/system/ip/system_rate_1_1/system_rate_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rate_1_1 || ORIG_REF_NAME==system_rate_1_1} -quiet] -quiet

# IP: bd/system/ip/system_cic_0_1/system_cic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cic_0_1 || ORIG_REF_NAME==system_cic_0_1} -quiet] -quiet

# IP: bd/system/ip/system_cic_1_1/system_cic_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cic_1_1 || ORIG_REF_NAME==system_cic_1_1} -quiet] -quiet

# IP: bd/system/ip/system_comb_0_2/system_comb_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_comb_0_2 || ORIG_REF_NAME==system_comb_0_2} -quiet] -quiet

# IP: bd/system/ip/system_phase_0_1/system_phase_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_phase_0_1 || ORIG_REF_NAME==system_phase_0_1} -quiet] -quiet

# IP: bd/system/ip/system_dds_0_1/system_dds_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_dds_0_1 || ORIG_REF_NAME==system_dds_0_1} -quiet] -quiet

# IP: bd/system/ip/system_lfsr_0_1/system_lfsr_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_lfsr_0_1 || ORIG_REF_NAME==system_lfsr_0_1} -quiet] -quiet

# IP: bd/system/ip/system_mult_0_1/system_mult_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_mult_0_1 || ORIG_REF_NAME==system_mult_0_1} -quiet] -quiet

# IP: bd/system/ip/system_concat_0_0/system_concat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_concat_0_0 || ORIG_REF_NAME==system_concat_0_0} -quiet] -quiet

# IP: bd/system/ip/system_hub_0_1/system_hub_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_hub_0_1 || ORIG_REF_NAME==system_hub_0_1} -quiet] -quiet

# IP: bd/system/ip/system_rst_slice_0_1/system_rst_slice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_slice_0_1 || ORIG_REF_NAME==system_rst_slice_0_1} -quiet] -quiet

# IP: bd/system/ip/system_rst_slice_1_1/system_rst_slice_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_slice_1_1 || ORIG_REF_NAME==system_rst_slice_1_1} -quiet] -quiet

# IP: bd/system/ip/system_cfg_slice_0_1/system_cfg_slice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cfg_slice_0_1 || ORIG_REF_NAME==system_cfg_slice_0_1} -quiet] -quiet

# IP: bd/system/ip/system_cfg_slice_1_1/system_cfg_slice_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cfg_slice_1_1 || ORIG_REF_NAME==system_cfg_slice_1_1} -quiet] -quiet

# IP: bd/system/ip/system_slice_0_2/system_slice_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_0_2 || ORIG_REF_NAME==system_slice_0_2} -quiet] -quiet

# IP: bd/system/ip/system_slice_1_2/system_slice_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_1_2 || ORIG_REF_NAME==system_slice_1_2} -quiet] -quiet

# IP: bd/system/ip/system_slice_2_2/system_slice_2_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_2_2 || ORIG_REF_NAME==system_slice_2_2} -quiet] -quiet

# IP: bd/system/ip/system_phase_0_2/system_phase_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_phase_0_2 || ORIG_REF_NAME==system_phase_0_2} -quiet] -quiet

# IP: bd/system/ip/system_dds_0_2/system_dds_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_dds_0_2 || ORIG_REF_NAME==system_dds_0_2} -quiet] -quiet

# IP: bd/system/ip/system_lfsr_0_2/system_lfsr_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_lfsr_0_2 || ORIG_REF_NAME==system_lfsr_0_2} -quiet] -quiet

# IP: bd/system/ip/system_mult_0_2/system_mult_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_mult_0_2 || ORIG_REF_NAME==system_mult_0_2} -quiet] -quiet

# IP: bd/system/ip/system_bcast_0_3/system_bcast_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bcast_0_3 || ORIG_REF_NAME==system_bcast_0_3} -quiet] -quiet

# IP: bd/system/ip/system_rate_0_2/system_rate_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rate_0_2 || ORIG_REF_NAME==system_rate_0_2} -quiet] -quiet

# IP: bd/system/ip/system_rate_1_2/system_rate_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rate_1_2 || ORIG_REF_NAME==system_rate_1_2} -quiet] -quiet

# IP: bd/system/ip/system_cic_0_2/system_cic_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cic_0_2 || ORIG_REF_NAME==system_cic_0_2} -quiet] -quiet

# IP: bd/system/ip/system_cic_1_2/system_cic_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cic_1_2 || ORIG_REF_NAME==system_cic_1_2} -quiet] -quiet

# IP: bd/system/ip/system_comb_0_3/system_comb_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_comb_0_3 || ORIG_REF_NAME==system_comb_0_3} -quiet] -quiet

# IP: bd/system/ip/system_conv_0_2/system_conv_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_conv_0_2 || ORIG_REF_NAME==system_conv_0_2} -quiet] -quiet

# IP: bd/system/ip/system_fir_0_2/system_fir_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_fir_0_2 || ORIG_REF_NAME==system_fir_0_2} -quiet] -quiet

# IP: bd/system/ip/system_subset_0_1/system_subset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_subset_0_1 || ORIG_REF_NAME==system_subset_0_1} -quiet] -quiet

# IP: bd/system/ip/system_fp_0_2/system_fp_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_fp_0_2 || ORIG_REF_NAME==system_fp_0_2} -quiet] -quiet

# IP: bd/system/ip/system_conv_1_2/system_conv_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_conv_1_2 || ORIG_REF_NAME==system_conv_1_2} -quiet] -quiet

# IP: bd/system/ip/system_fifo_0_2/system_fifo_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_fifo_0_2 || ORIG_REF_NAME==system_fifo_0_2} -quiet] -quiet

# IP: bd/system/ip/system_slice_0_3/system_slice_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_0_3 || ORIG_REF_NAME==system_slice_0_3} -quiet] -quiet

# IP: bd/system/ip/system_slice_1_3/system_slice_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_1_3 || ORIG_REF_NAME==system_slice_1_3} -quiet] -quiet

# IP: bd/system/ip/system_slice_2_3/system_slice_2_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_2_3 || ORIG_REF_NAME==system_slice_2_3} -quiet] -quiet

# IP: bd/system/ip/system_fifo_0_3/system_fifo_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_fifo_0_3 || ORIG_REF_NAME==system_fifo_0_3} -quiet] -quiet

# IP: bd/system/ip/system_conv_0_3/system_conv_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_conv_0_3 || ORIG_REF_NAME==system_conv_0_3} -quiet] -quiet

# IP: bd/system/ip/system_fp_0_3/system_fp_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_fp_0_3 || ORIG_REF_NAME==system_fp_0_3} -quiet] -quiet

# IP: bd/system/ip/system_fir_0_3/system_fir_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_fir_0_3 || ORIG_REF_NAME==system_fir_0_3} -quiet] -quiet

# IP: bd/system/ip/system_conv_1_3/system_conv_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_conv_1_3 || ORIG_REF_NAME==system_conv_1_3} -quiet] -quiet

# IP: bd/system/ip/system_bcast_0_4/system_bcast_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bcast_0_4 || ORIG_REF_NAME==system_bcast_0_4} -quiet] -quiet

# IP: bd/system/ip/system_rate_0_3/system_rate_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rate_0_3 || ORIG_REF_NAME==system_rate_0_3} -quiet] -quiet

# IP: bd/system/ip/system_rate_1_3/system_rate_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rate_1_3 || ORIG_REF_NAME==system_rate_1_3} -quiet] -quiet

# IP: bd/system/ip/system_cic_0_3/system_cic_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cic_0_3 || ORIG_REF_NAME==system_cic_0_3} -quiet] -quiet

# IP: bd/system/ip/system_cic_1_3/system_cic_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cic_1_3 || ORIG_REF_NAME==system_cic_1_3} -quiet] -quiet

# IP: bd/system/ip/system_comb_0_4/system_comb_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_comb_0_4 || ORIG_REF_NAME==system_comb_0_4} -quiet] -quiet

# IP: bd/system/ip/system_phase_0_3/system_phase_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_phase_0_3 || ORIG_REF_NAME==system_phase_0_3} -quiet] -quiet

# IP: bd/system/ip/system_dds_0_3/system_dds_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_dds_0_3 || ORIG_REF_NAME==system_dds_0_3} -quiet] -quiet

# IP: bd/system/ip/system_lfsr_0_3/system_lfsr_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_lfsr_0_3 || ORIG_REF_NAME==system_lfsr_0_3} -quiet] -quiet

# IP: bd/system/ip/system_mult_0_3/system_mult_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_mult_0_3 || ORIG_REF_NAME==system_mult_0_3} -quiet] -quiet

# IP: bd/system/ip/system_concat_0_1/system_concat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_concat_0_1 || ORIG_REF_NAME==system_concat_0_1} -quiet] -quiet

# IP: bd/system/ip/system_fifo_0_4/system_fifo_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_fifo_0_4 || ORIG_REF_NAME==system_fifo_0_4} -quiet] -quiet

# IP: bd/system/ip/system_spi_0_0/system_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_spi_0_0 || ORIG_REF_NAME==system_spi_0_0} -quiet] -quiet

# IP: bd/system/ip/system_fifo_1_0/system_fifo_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_fifo_1_0 || ORIG_REF_NAME==system_fifo_1_0} -quiet] -quiet

# IP: bd/system/ip/system_spi_1_0/system_spi_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_spi_1_0 || ORIG_REF_NAME==system_spi_1_0} -quiet] -quiet

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_pll_0_0/system_pll_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_pll_0_0 || ORIG_REF_NAME==system_pll_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_pll_0_0/system_pll_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_pll_0_0 || ORIG_REF_NAME==system_pll_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_pll_0_0/system_pll_0_0_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_ps_0_0/system_ps_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ps_0_0 || ORIG_REF_NAME==system_ps_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_rst_0_0/system_rst_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_0_0 || ORIG_REF_NAME==system_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_rst_0_0/system_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_0_0 || ORIG_REF_NAME==system_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_bcast_0_0/system_bcast_0_0_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_dds_0_0/system_dds_0_0_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_mult_0_0/system_mult_0_0_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_bcast_0_1/system_bcast_0_1_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_cic_0_0/system_cic_0_0_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_cic_1_0/system_cic_1_0_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_comb_0_1/system_comb_0_1_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_conv_0_0/system_conv_0_0_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_fir_0_0/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fir_0_0 || ORIG_REF_NAME==system_fir_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_fir_0_0/system_fir_0_0_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_subset_0_0/system_subset_0_0_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_fp_0_0/system_fp_0_0_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_conv_1_0/system_conv_1_0_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_conv_0_1/system_conv_0_1_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_fp_0_1/system_fp_0_1_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_fir_0_1/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fir_0_1 || ORIG_REF_NAME==system_fir_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_fir_0_1/system_fir_0_1_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_conv_1_1/system_conv_1_1_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_bcast_0_2/system_bcast_0_2_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_cic_0_1/system_cic_0_1_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_cic_1_1/system_cic_1_1_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_comb_0_2/system_comb_0_2_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_dds_0_1/system_dds_0_1_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_mult_0_1/system_mult_0_1_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_dds_0_2/system_dds_0_2_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_mult_0_2/system_mult_0_2_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_bcast_0_3/system_bcast_0_3_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_cic_0_2/system_cic_0_2_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_cic_1_2/system_cic_1_2_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_comb_0_3/system_comb_0_3_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_conv_0_2/system_conv_0_2_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_fir_0_2/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fir_0_2 || ORIG_REF_NAME==system_fir_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_fir_0_2/system_fir_0_2_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_subset_0_1/system_subset_0_1_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_fp_0_2/system_fp_0_2_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_conv_1_2/system_conv_1_2_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_conv_0_3/system_conv_0_3_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_fp_0_3/system_fp_0_3_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_fir_0_3/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fir_0_3 || ORIG_REF_NAME==system_fir_0_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_fir_0_3/system_fir_0_3_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_conv_1_3/system_conv_1_3_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_bcast_0_4/system_bcast_0_4_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_cic_0_3/system_cic_0_3_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_cic_1_3/system_cic_1_3_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_comb_0_4/system_comb_0_4_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_dds_0_3/system_dds_0_3_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/ip/system_mult_0_3/system_mult_0_3_ooc.xdc

# XDC: /home/andrew/eclypse-z7-notes/tmp/sdr_transceiver.gen/sources_1/bd/system/system_ooc.xdc
