set_property SRC_FILE_INFO {cfile:b:/OneDrive/OneDrive/_School/QORVO_RADIO/Github/PYNQ/PYNQ_PLL_TEST/PYNQ_PLL_TEST.gen/sources_1/bd/MainDesign/ip/MainDesign_ClockDivider_1_0/MainDesign_ClockDivider_1_0/MainDesign_ClockDivider_1_0_in_context.xdc rfile:../../../../../PYNQ_PLL_TEST.gen/sources_1/bd/MainDesign/ip/MainDesign_ClockDivider_1_0/MainDesign_ClockDivider_1_0/MainDesign_ClockDivider_1_0_in_context.xdc id:1 order:EARLY scoped_inst:MainDesign_i/ClockDivider_1} [current_design]
set_property SRC_FILE_INFO {cfile:b:/OneDrive/OneDrive/_School/QORVO_RADIO/Github/PYNQ/PYNQ_PLL_TEST/PYNQ_PLL_TEST.gen/sources_1/bd/MainDesign/ip/MainDesign_ClockDivider_2_0/MainDesign_ClockDivider_2_0/MainDesign_ClockDivider_2_0_in_context.xdc rfile:../../../../../PYNQ_PLL_TEST.gen/sources_1/bd/MainDesign/ip/MainDesign_ClockDivider_2_0/MainDesign_ClockDivider_2_0/MainDesign_ClockDivider_2_0_in_context.xdc id:2 order:EARLY scoped_inst:MainDesign_i/ClockDivider_2} [current_design]
set_property SRC_FILE_INFO {cfile:b:/OneDrive/OneDrive/_School/QORVO_RADIO/Github/PYNQ/PYNQ_PLL_TEST/PYNQ_PLL_TEST.gen/sources_1/bd/MainDesign/ip/MainDesign_ClockDivider_3_0/MainDesign_ClockDivider_3_0/MainDesign_ClockDivider_3_0_in_context.xdc rfile:../../../../../PYNQ_PLL_TEST.gen/sources_1/bd/MainDesign/ip/MainDesign_ClockDivider_3_0/MainDesign_ClockDivider_3_0/MainDesign_ClockDivider_3_0_in_context.xdc id:3 order:EARLY scoped_inst:MainDesign_i/ClockDivider_3} [current_design]
set_property SRC_FILE_INFO {cfile:b:/OneDrive/OneDrive/_School/QORVO_RADIO/Github/PYNQ/PYNQ_PLL_TEST/PYNQ_PLL_TEST.gen/sources_1/bd/MainDesign/ip/MainDesign_ClockDivider_4_0/MainDesign_ClockDivider_4_0/MainDesign_ClockDivider_4_0_in_context.xdc rfile:../../../../../PYNQ_PLL_TEST.gen/sources_1/bd/MainDesign/ip/MainDesign_ClockDivider_4_0/MainDesign_ClockDivider_4_0/MainDesign_ClockDivider_4_0_in_context.xdc id:4 order:EARLY scoped_inst:MainDesign_i/ClockDivider_4} [current_design]
set_property SRC_FILE_INFO {cfile:B:/OneDrive/OneDrive/_School/QORVO_RADIO/Github/PYNQ/PYNQ_PLL_TEST/PYNQ_PLL_TEST.srcs/constrs_1/new/Constraints.xdc rfile:../../../../../PYNQ_PLL_TEST.srcs/constrs_1/new/Constraints.xdc id:5} [current_design]
set_property SRC_FILE_INFO {cfile:B:/OneDrive/OneDrive/_School/QORVO_RADIO/Github/PYNQ/PYNQ_PLL_TEST/PYNQ_PLL_TEST.runs/synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:6} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells MainDesign_i/ClockDivider_1]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells MainDesign_i/ClockDivider_2]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells MainDesign_i/ClockDivider_3]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells MainDesign_i/ClockDivider_4]
set_property src_info {type:XDC file:5 line:9 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports CLK_IN]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells MainDesign_i]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells MainDesign_i/ClockDivider_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells MainDesign_i/ClockDivider_2]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells MainDesign_i/ClockDivider_3]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells MainDesign_i/ClockDivider_4]
